# Generated by Django 5.0.3 on 2024-04-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('profile', models.ImageField(upload_to='shop/profile')),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
